/*
MobileWeb Auth Localization
名稱：會員介面繁體中文字串
說明：覆寫 @neondatabase/auth-ui（better-auth-ui）的預設英文字串。
      只翻譯 Email + 密碼登入、註冊、忘記密碼與帳號設定會出現的字串；未列出的沿用套件預設值

[Change Log]
--------------------------------------------------------------------------------
Format: [YYYY-MM-DD] [Author] [Description]
Rule: One change per line. Append new entries at the bottom.
--------------------------------------------------------------------------------
[2026-10-03] [flyqazwsx] [系統初版／會員註冊登入]
*/

import { authLocalization, type AuthLocalization } from "@neondatabase/auth-ui/server";

/** 繁體中文覆寫字串 */
const objZhTwOverrides: Partial<AuthLocalization> = {
    ACCOUNT: "帳號",
    ALREADY_HAVE_AN_ACCOUNT: "已經有帳號了？",
    AVATAR: "大頭貼",
    AVATAR_DESCRIPTION: "點選大頭貼可從檔案上傳自訂圖片。",
    AVATAR_INSTRUCTIONS: "大頭貼可不設定。",
    CANCEL: "取消",
    CHANGE_PASSWORD: "變更密碼",
    CHANGE_PASSWORD_DESCRIPTION: "輸入目前的密碼與新密碼。",
    CHANGE_PASSWORD_INSTRUCTIONS: "密碼至少 8 個字元。",
    CHANGE_PASSWORD_SUCCESS: "密碼已變更。",
    CONFIRM_PASSWORD: "確認密碼",
    CONFIRM_PASSWORD_PLACEHOLDER: "再輸入一次密碼",
    CONFIRM_PASSWORD_REQUIRED: "請再輸入一次密碼",
    CONTINUE: "繼續",
    CURRENT_PASSWORD: "目前的密碼",
    CURRENT_PASSWORD_PLACEHOLDER: "目前的密碼",
    CURRENT_SESSION: "目前的登入裝置",
    DELETE: "刪除",
    DELETE_ACCOUNT: "刪除帳號",
    DELETE_ACCOUNT_DESCRIPTION: "永久刪除帳號與所有資料，刪除後無法復原。",
    DELETE_ACCOUNT_INSTRUCTIONS: "請確認要刪除帳號，刪除後無法復原。",
    DELETE_ACCOUNT_SUCCESS: "帳號已刪除。",
    DELETE_ACCOUNT_VERIFY: "請到信箱確認刪除帳號。",
    DELETE_AVATAR: "刪除大頭貼",
    DONE: "完成",
    DONT_HAVE_AN_ACCOUNT: "還沒有帳號？",
    EMAIL: "電子郵件",
    EMAIL_DESCRIPTION: "輸入登入用的電子郵件。",
    EMAIL_INSTRUCTIONS: "請輸入有效的電子郵件。",
    EMAIL_IS_THE_SAME: "電子郵件沒有變更",
    EMAIL_PLACEHOLDER: "name@example.com",
    EMAIL_REQUIRED: "請輸入電子郵件",
    EMAIL_VERIFICATION: "驗證電子郵件",
    EMAIL_VERIFICATION_DESCRIPTION: "請到信箱查看驗證碼以完成註冊。",
    EMAIL_VERIFICATION_SUCCESS: "電子郵件驗證成功。",
    EMAIL_VERIFY_CHANGE: "請到信箱確認變更。",
    FORGOT_PASSWORD: "忘記密碼",
    FORGOT_PASSWORD_ACTION: "寄送重設連結",
    FORGOT_PASSWORD_DESCRIPTION: "輸入電子郵件以重設密碼",
    FORGOT_PASSWORD_EMAIL: "請到信箱查看重設密碼連結。",
    FORGOT_PASSWORD_LINK: "忘記密碼？",
    GO_BACK: "返回",
    IS_INVALID: "格式不正確",
    IS_REQUIRED: "為必填",
    IS_THE_SAME: "沒有變更",
    NAME: "名稱",
    NAME_DESCRIPTION: "請輸入姓名或顯示名稱。",
    NAME_INSTRUCTIONS: "最多 32 個字元。",
    NAME_PLACEHOLDER: "名稱",
    NEW_PASSWORD: "新密碼",
    NEW_PASSWORD_PLACEHOLDER: "新密碼",
    NEW_PASSWORD_REQUIRED: "請輸入新密碼",
    OPTIONAL_BRACKETS: "（選填）",
    OR_CONTINUE_WITH: "或使用以下方式",
    PASSWORD: "密碼",
    PASSWORD_PLACEHOLDER: "密碼",
    PASSWORD_REQUIRED: "請輸入密碼",
    PASSWORDS_DO_NOT_MATCH: "兩次輸入的密碼不一致",
    REMEMBER_ME: "記住我",
    REQUEST_FAILED: "要求失敗",
    RESEND_VERIFICATION_EMAIL: "重新寄送驗證信",
    RESET_PASSWORD: "重設密碼",
    RESET_PASSWORD_ACTION: "儲存新密碼",
    RESET_PASSWORD_DESCRIPTION: "請輸入新密碼",
    RESET_PASSWORD_SUCCESS: "密碼已重設",
    REVOKE: "登出此裝置",
    SAVE: "儲存",
    SECURITY: "安全性",
    SESSIONS: "登入裝置",
    SESSIONS_DESCRIPTION: "管理目前登入中的裝置，可將其登出。",
    SESSION_NOT_FRESH: "登入已過一段時間，請重新登入。",
    SET_PASSWORD: "設定密碼",
    SETTINGS: "帳號設定",
    SIGN_IN: "登入",
    SIGN_IN_ACTION: "登入",
    SIGN_IN_DESCRIPTION: "輸入電子郵件與密碼登入帳號",
    SIGN_OUT: "登出",
    SIGN_UP: "註冊",
    SIGN_UP_ACTION: "建立帳號",
    SIGN_UP_DESCRIPTION: "填寫資料建立新帳號",
    SIGN_UP_EMAIL: "請到信箱點選驗證連結。",
    UPDATE: "更新",
    UPDATED_SUCCESSFULLY: "已更新",
    UPLOAD_AVATAR: "上傳大頭貼",
    USER: "使用者",
    VERIFY_YOUR_EMAIL: "驗證電子郵件",
    VERIFY_YOUR_EMAIL_DESCRIPTION: "請驗證電子郵件，到收件匣查看驗證信；沒收到的話可以按下方按鈕重新寄送。",

    // 錯誤訊息
    ACCOUNT_NOT_FOUND: "找不到帳號",
    CREDENTIAL_ACCOUNT_NOT_FOUND: "找不到此帳號的密碼設定",
    EMAIL_NOT_VERIFIED: "電子郵件尚未驗證",
    FAILED_TO_CREATE_USER: "建立帳號失敗",
    FAILED_TO_CREATE_SESSION: "登入失敗",
    FAILED_TO_UPDATE_USER: "更新帳號失敗",
    INVALID_EMAIL: "電子郵件格式不正確",
    INVALID_EMAIL_OR_PASSWORD: "電子郵件或密碼錯誤",
    INVALID_PASSWORD: "密碼錯誤",
    INVALID_TOKEN: "連結無效或已過期",
    PASSWORD_COMPROMISED: "這組密碼曾出現在外洩資料中，請改用其他密碼。",
    PASSWORD_TOO_LONG: "密碼太長",
    PASSWORD_TOO_SHORT: "密碼太短（至少 8 個字元）",
    RATE_LIMIT_EXCEEDED: "嘗試次數過多，請稍後再試。",
    SESSION_EXPIRED: "登入已過期，請重新登入後再操作。",
    TOO_MANY_ATTEMPTS: "嘗試次數過多",
    UNKNOWN_ERROR: "發生錯誤，請稍後再試",
    USER_ALREADY_EXISTS: "這個電子郵件已經註冊過",
    USER_NOT_FOUND: "找不到使用者",
};

/** 完整字串表：套件預設值 + 繁體中文覆寫 */
export const objZhTwLocalization: AuthLocalization = { ...authLocalization, ...objZhTwOverrides };
